services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shopnest-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ShopNest_Strong!2026"
    ports:
      - "1433:1433"
    volumes:
      - shopnest_sql_data:/var/opt/mssql

volumes:
  shopnest_sql_data:
